### ISSUE TITLE
Add instruction how to use containers with github actions

### ISSUE THREAD

**Issue by qarmin** [MGlolenstine/gtk4-cross#16]
I wanted to integrate this repository into my project CI, but for now I have no idea how could I do this (https://github.com/qarmin/czkawka/pull/749).
Currently I stopped on this code
```
name: 🏁 Windows
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  windows-gui-release-normal-app:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: mglolenstine/gtk4-cross:rust-gtk-4.6
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
          git clone https://github.com/qarmin/czkawka.git
          build
          zip -r gtk_app.zip target/x86_64-pc-windows-gnu/release/czkawka_gui.exe
        name: Run in container
      - name: Store Windows GUI CrossComplile
        uses: actions/upload-artifact@v2
        with:
          name: czkawka_gui-release-console-${{ matrix.toolchain }}
          path: gtk_app.zip
```
which shows error
```
/usr/bin/build: line 4: /github/home/.cargo/env: No such file or directory
```
